server:
  port: 80
  
spring:
 #数据库的配置
  datasource:
    name: datasource
    initialize: false
    url: jdbc:mysql://localhost:3306/xqxx_nfdw?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true
    
    
#springMvc的配置
  mvc:
     view:
       prefix: /WEB-INF/views/
       suffix: .jsp
     servlet:
       load-on-startup: 1
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss      
#日志
logging:
  config: classpath:logback-spring.xml
  file: D:/SSMM/logs/springboot.log  
#静态文件后缀
web:
  staticFile: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk
#自定义变量
disk: d://    